### ISSUE TITLE
preinst script breaks on servers with restricted networks

### ISSUE THREAD

**Issue by dsalvador-dsalvador** [DataDog/dd-agent-omnibus#144]
On Debian based systems, the preinst script in the .deb package causes a failure when attempting to retrieve PGP keys.

I submitted a pull request which checks for existing PGP keys in apt-key, and also checks if a proxy is in use.
https://github.com/DataDog/dd-agent-omnibus/pull/143

**Comment by olivielpeau** [comment]
This was fixed with #143, closing (and thanks again for the fix ;) )
