### ISSUE TITLE
auto_conf files not copied in the package

### ISSUE THREAD

**Issue by masci** [DataDog/dd-agent-omnibus#147]
After a clean installation of the `5.12.0~rc.6` on Xenial, the folder `/etc/dd-agent/conf.d/auto_conf` is empty.
The culprit might be this: https://github.com/DataDog/dd-agent-omnibus/blob/master/config/software/datadog-agent-integrations.rb#L101 the name of the file is missing an underscore.

**Comment by gmmeyer** [comment]
I have a PR to fix this, referenced above. We can close it after that's merged. Thanks! This is a good find.
