### ISSUE TITLE
Build error with datadog-gohai

### ISSUE THREAD

**Issue by luhkevin** [DataDog/dd-agent-omnibus#170]
Not exactly sure where to put this, but I'm getting a build error when I build `dd-agent` with the latest changes to gohai:

```
 [Builder: datadog-gohai] I | 2017-05-01T21:32:50+00:00 | Execute: `/usr/local/go/bin/go get -d -u github.com/DataDog/gohai': 1.145s
 [Builder: datadog-gohai] I | 2017-05-01T21:32:50+00:00 | Build datadog-gohai: 1.5283s
The following shell command exited with status 1:

    $ GOPATH=/var/cache/omnibus/src/datadog-gohai GOROOT=/usr/local/go /usr/local/go/bin/go get -d -u github.com/DataDog/gohai

Output:

    (nothing)

Error:

    package github.com/DataDog/gohai
	imports context: unrecognized import path "context"
```

Seems like this was recently merged: https://github.com/shirou/gopsutil/commit/772ab1fdbcd76ae2067ea5ca6052181fce941361

and `"context"` depends on `go >= 1.5`, but the version of `go` in `datadog/docker-dd-agent-build-deb-x64` is 1.3.3.

How is the build working for you guys?

**Comment by masci** [comment]
Hi @luhkevin thanks for reporting this. 

We build gohai against the `last_stable` branch that pins a version of gopsutil that doesn't have that commit - so far, so good. 
We already have the plan to increase the Go version in our builders but this definitely puts some pressure in doing that, will leave this issue opened until we address it.

**Comment by olivielpeau** [comment]
Fixed with https://github.com/DataDog/omnibus-software/pull/138 (transitional fix until we upgrade to a more recent version of go), thanks again @luhkevin your feedback!
