### ISSUE TITLE
Bundle changelog in packaged dd-agent

### ISSUE THREAD

**Issue by LeoCavaille** [DataDog/dd-agent-omnibus#56]
In debian-style packages, one can update the `debian/changelog` file with information for new releases.
This usually shows in "need upgrading" reports (such as apticron's), and they're pretty useful for sysadmins.
I don't know if omnibus supports this.

https://www.debian.org/doc/debian-policy/ch-source.html#s-dpkgchangelog

```
apticron report [Tue, 17 Nov 2015 09:09:18 +0100]
========================================================================

apticron has detected that some packages need upgrading on:

    XXXX 
    [ xxx.xxx.xxx.xxx xxxx:xxxx:xxxx:xxxx::1 ]

The following packages are currently pending an upgrade:

    datadog-agent 1:5.6.2-1


========================================================================

Package Details:

Reading changelogs...
========================================================================
```

**Comment by olivielpeau** [comment]
After having a quick look around it doesn't seem that Omnibus supports this out-of-the-box.

**Comment by olivielpeau** [comment]
No customer demand for this, and omnibus doesn't support it out of the box. We're not going to prioritize this. Closing.
