### ISSUE TITLE
apt postinst script

### ISSUE THREAD

**Issue by suhasgaddam** [DataDog/dd-agent-omnibus#93]
I noticed that datadog-agent 5.9.0-1 debian packages do not have the updated postinst from https://github.com/DataDog/dd-agent-omnibus/pull/89.

As far as I can tell, https://github.com/DataDog/dd-agent-omnibus/commit/55d0ea8ad39b802e388ae7ec66f02efb8c3d7819 exists in `5.9.0` and https://github.com/DataDog/dd-agent-omnibus/pull/89 shows up in https://github.com/DataDog/dd-agent/releases/tag/5.9.0

Is there anything I am missing?

https://s3.amazonaws.com/apt.datadoghq.com/pool/d/da/datadog-agent_5.9.0-1_amd64.deb
https://s3.amazonaws.com/apt.datadoghq.com/pool/d/da/datadog-agent_5.9.0-1_i386.deb

from

http://apt.datadoghq.com/pool/d/da/

**Comment by olivielpeau** [comment]
Hi @suhasgaddam, thanks for bringing this up, there is indeed an issue with the `5.9.0` package: it was built with a slightly older version of `dd-agent-omnibus` (https://github.com/DataDog/dd-agent-omnibus/commit/15f35f036d03e93c06ede54f388a56cfa089efde to be accurate), so in particular your changes weren't built in the `5.9.0` package. We're working on fixing that in a `5.9.1` release, should be out by tomorrow (I'll update this issue when it's released).

We're also taking steps to ensure this doesn't happen again in the future. Thanks again for your feedback!

**Comment by suhasgaddam** [comment]
Thanks. The updated postinst script exists in `5.9.1`.
